#!/bin/bash
# usage: tex-here <document-name> [workspace-for-shell] [workspace-for-editor] [workspace-for-pdf-viewer]
DOC_NAME=$1
SHELL_WORKSPACE_ID=$(workspace-name-to-id ${2:-m1})
EDITOR_WORKSPACE_ID=$(workspace-name-to-id ${3:-c1})
PDF_VIEWER_WORKSPACE_ID=$(workspace-name-to-id ${4:-c2})

HELPER_SCRIPT=`mktemp -t tex-here-$DOC_NAME-helper-XXX`

chmod +x $HELPER_SCRIPT
cat > $HELPER_SCRIPT <<EOF
#!/bin/sh
# create an empty PDF, to be replaced in the compilation process
echo | ps2pdf - $DOC_NAME.pdf
xdg-open $DOC_NAME.pdf &
# If your PDF viewer does not take focus you can also try 
# xdotool search --class ... (for class found by xprop or xwininfo)
sleep 0.5; wmctrl -r :ACTIVE: -t $PDF_VIEWER_WORKSPACE_ID

$EDITOR $DOC_NAME.tex &
# Ideally we'd like to switch window opened by the child process, not
# the active window. In case of emacs the window is controlled by
# the master emacs process, not the emacsclient whose PID we'd get, so
# we switch the active window.
sleep 0.5; wmctrl -r :ACTIVE: -t $EDITOR_WORKSPACE_ID
wmctrl -s $EDITOR_WORKSPACE_ID

latexmk -C $DOC_NAME
latexmk -pdf -pvc $DOC_NAME
echo TeXer died...
read _
exec rm $HELPER_SCRIPT
EOF

wmctrl -r :ACTIVE: -t $SHELL_WORKSPACE_ID

tmux \
    new-session -s tex-$DOC_NAME -n pdf $HELPER_SCRIPT \; \
    new-window -n err 'check-latex-errors loop' \; \
    new-window -n prog 'git-progress loop'
