#!/bin/bash
# usage: tex-here <document-name> [workspace-for-shell] [workspace-for-editor] [workspace-for-pdf-viewer]
TEX_HERE_DB="$HOME/var/tex-here.json"
LATEX_DEFAULT_ARGS="-synctex=1"

DOC_NAME=${1%.tex}
SHELL_WORKSPACE_ID=$(workspace-name-to-id ${2:-c1})
EDITOR_WORKSPACE_ID=$(workspace-name-to-id ${3:-c1})
PDF_VIEWER_WORKSPACE_ID=$(workspace-name-to-id ${4:-c2})

###############################################################################

CANONICAL_PATH=$(readlink -f $DOC_NAME.tex)

if [ ! -e $CANONICAL_PATH ]; then
    echo "$CANONICAL_PATH does not exist."
    exit 1
fi

if [ ! -s $TEX_HERE_DB ]; then
    echo "$TEX_HERE_DB empty, adding placeholder map."
    echo "{}" > $TEX_HERE_DB
fi

###############################################################################
get_tex_here_var()
{
    jq -r \
        --arg CANONICAL_PATH "$CANONICAL_PATH" \
        --arg VAR "$1" \
        --arg DEFAULT "$2" \
        '(.[$CANONICAL_PATH] // {})[$VAR] // $DEFAULT' \
        $TEX_HERE_DB
}

LATEX_CMD=$(get_tex_here_var latex-cmd pdflatex)
LATEX_EXTRA_ARGS=$(get_tex_here_var latex-extra-args "")
PRE_LATEXRUN_CMD=$(get_tex_here_var pre-latexrun-cmd "")
POST_LATEXRUN_CMD=$(get_tex_here_var post-latexrun-cmd "")
###############################################################################

LATEX_ARGS="$LATEX_DEFAULT_ARGS $LATEX_EXTRA_ARGS"

HELPER_SCRIPT=`mktemp -t tex-here-$DOC_NAME-helper-XXX`

chmod +x $HELPER_SCRIPT
cat > $HELPER_SCRIPT <<EOF
#!/bin/bash
trap "rm $HELPER_SCRIPT" EXIT

# create an empty PDF, to be replaced in the compilation process
echo "%!PS\nshowpage\n%%EOF" | ps2pdf - $DOC_NAME.pdf
# set it to have placeholder outline (/Title), open at page 1
# (/PageMode /Page 1), outlines open (/UseOutlines), fitting page bounding
# box to the window (/FitB), and continuous (/OneColumn)
# http://extras.springer.com/1998/978-3-642-72032-1/PDF/PRIMER.PDF
# https://www.tug.org/applications/hyperref/manual.html
gs \
   -q -dBATCH -dNOPAUSE \
   -o $DOC_NAME.pdf \
   -sDEVICE=pdfwrite \
   -c "[ /Title (Title Page) /Page 1 /OUT pdfmark" \
   -c "[ /PageMode /UseOutlines /Page 1 /View [ /FitB ] /DOCVIEW pdfmark" \
   -c "[ {Catalog} << /PageLayout /OneColumn >> /PUT pdfmark" \
   -f $DOC_NAME.pdf

# xdg-open associations are hard to change so just hard-code evince
evince $DOC_NAME.pdf &

# If your PDF viewer does not take focus you can also try
# xdotool search --class ... (for class found by xprop or xwininfo)
sleep 0.5; wmctrl -r :ACTIVE: -t $PDF_VIEWER_WORKSPACE_ID

$EDITOR $DOC_NAME.tex &
# Ideally we'd like to switch window opened by the child process, not
# the active window. In case of emacs the window is controlled by
# the master emacs process, not the emacsclient whose PID we'd get, so
# we switch the active window.
sleep 0.5; wmctrl -r :ACTIVE: -t $EDITOR_WORKSPACE_ID
wmctrl -s $EDITOR_WORKSPACE_ID

# latexrun --clean-all
mkdir -p latex.out
rm -f $DOC_NAME.synctex.gz
ln -sfn latex.out/$DOC_NAME.synctex.gz $DOC_NAME.synctex.gz

REASON="(initial launch)"
while true; do
      clear
      echo [+] Compilation reason: \$REASON
      if [ "$PRE_LATEXRUN_CMD" != "" ]; then
          echo [+] Executing pre-latexrun command: $PRE_LATEXRUN_CMD
          $PRE_LATEXRUN_CMD
      fi
      echo [+] latexrun command: $LATEX_CMD $LATEX_ARGS
      echo [+] latexrun started: \$(date "+%Y-%m-%d %H:%M:%S")
      latexrun \
         --latex-cmd="$LATEX_CMD" \
         --latex-args="$LATEX_ARGS" \
         $DOC_NAME
      echo [+] latexrun done: \$(date "+%Y-%m-%d %H:%M:%S")
      if [ "$POST_LATEXRUN_CMD" != "" ]; then
          echo [+] Executing post-latexrun command: $POST_LATEXRUN_CMD
          $POST_LATEXRUN_CMD
      fi
      jq --raw-output \
         '.tasks[].deps | map(select(.[0] == "file" and .[2] != null)) | .[][1][]' \
         latex.out/.latexrun.db | \
         grep -v '^/dev/null$' > latex.out/.tex-here.depends
      inotifywait \
         --quiet \
         --fromfile latex.out/.tex-here.depends \
         --event modify,move_self,delete_self,unmount 2>&1 > latex.out/.tex-here.inotifywait.out
      INOTIFY_RESULT=\$?
      if [ \$INOTIFY_RESULT -ne 0 ]; then
          cat latex.out/.tex-here.inotifywait.out
          sleep 5
      fi
      REASON=\$(egrep -v "^(Setting up watches\.|Watches established\.)\$" latex.out/.tex-here.inotifywait.out)
done
read _
EOF

wmctrl -r :ACTIVE: -t $SHELL_WORKSPACE_ID

echo "Starting $HELPER_SCRIPT in a tmux session."

tmux \
    new-session -s tex-$DOC_NAME -n compile $HELPER_SCRIPT \; \
    new-window -n prog 'git-progress loop' \; \
    select-window -t compile
