#!/bin/bash
TEX_HERE_DB="$HOME/var/tex-here.json"

if [ "$1" = "" ]; then
    echo "Usage: $0 main-tex-document"
    exit 0
fi

DOC_NAME=${1%.tex}
CANONICAL_PATH=$(readlink -f $DOC_NAME.tex)

if [ ! -e $CANONICAL_PATH ]; then
    echo "$CANONICAL_PATH does not exist."
    exit 1
fi

if [ ! -s $TEX_HERE_DB ]; then
    echo "$TEX_HERE_DB empty, adding placeholder map."
    echo "{}" > $TEX_HERE_DB
fi

###############################################################################
print_tex_here_vars()
{
    jq \
        --arg CANONICAL_PATH "$CANONICAL_PATH" \
        '.[$CANONICAL_PATH]' $TEX_HERE_DB
}

set_default_dict()
{
    jq \
        --arg CANONICAL_PATH "$CANONICAL_PATH" \
        '.[$CANONICAL_PATH] = (.[$CANONICAL_PATH] // {})' $TEX_HERE_DB | sponge $TEX_HERE_DB
}

update_tex_here_var()
{
    if [ "$2" = "" ]; then
        jq \
            --arg CANONICAL_PATH "$CANONICAL_PATH" \
            --arg VAR "$1" \
            'delpaths([[$CANONICAL_PATH, $VAR]])' $TEX_HERE_DB | sponge $TEX_HERE_DB
    else
        jq \
            --arg CANONICAL_PATH "$CANONICAL_PATH" \
            --arg VAR "$1" \
            --arg VAL "$2" \
            '.[$CANONICAL_PATH][$VAR] = $VAL' $TEX_HERE_DB | sponge $TEX_HERE_DB
    fi

}
###############################################################################

echo "Configuration before update:"
print_tex_here_vars

printf "Change these options? [n|y] "; read _cont
if [ X$_cont != Xy ]; then
    echo "tex-here database unchanged."
    exit 0
fi

printf "latex-cmd: "; read NEW_LATEX_CMD
printf "latex-extra-args: "; read NEW_LATEX_EXTRA_ARGS
printf "pre-latexrun-cmd: "; read NEW_PRE_LATEXRUN_CMD
printf "post-latexrun-cmd: "; read NEW_POST_LATEXRUN_CMD

set_default_dict
update_tex_here_var latex-cmd "$NEW_LATEX_CMD"
update_tex_here_var latex-extra-args "$NEW_LATEX_EXTRA_ARGS"
update_tex_here_var pre-latexrun-cmd "$NEW_PRE_LATEXRUN_CMD"
update_tex_here_var post-latexrun-cmd "$NEW_POST_LATEXRUN_CMD"

echo "Configuration after update:"
print_tex_here_vars
