#!/bin/bash
# usage: tex-here <document-name> [workspace-for-shell] [workspace-for-editor] [workspace-for-pdf-viewer]
DOC_NAME=${1%.tex}
SHELL_WORKSPACE_ID=$(workspace-name-to-id ${2:-m1})
EDITOR_WORKSPACE_ID=$(workspace-name-to-id ${3:-c1})
PDF_VIEWER_WORKSPACE_ID=$(workspace-name-to-id ${4:-c2})

HELPER_SCRIPT=`mktemp -t tex-here-$DOC_NAME-helper-XXX`

chmod +x $HELPER_SCRIPT
cat > $HELPER_SCRIPT <<EOF
#!/bin/sh
trap "{ rm $HELPER_SCRIPT }" EXIT

# create an empty PDF, to be replaced in the compilation process
echo -n | ps2pdf - $DOC_NAME.pdf
# add an outline so that PDF viewer will have it open for the real PDF as well
echo "[/Title (Title Page) /Page 1 /OUT pdfmark" |
    gs -dBATCH -dNOPAUSE -sDEVICE=pdfwrite -sOutputFile=$DOC_NAME.pdf $DOC_NAME.pdf /dev/stdin

xdg-open $DOC_NAME.pdf &
# If your PDF viewer does not take focus you can also try 
# xdotool search --class ... (for class found by xprop or xwininfo)
sleep 0.5; wmctrl -r :ACTIVE: -t $PDF_VIEWER_WORKSPACE_ID

$EDITOR $DOC_NAME.tex &
# Ideally we'd like to switch window opened by the child process, not
# the active window. In case of emacs the window is controlled by
# the master emacs process, not the emacsclient whose PID we'd get, so
# we switch the active window.
sleep 0.5; wmctrl -r :ACTIVE: -t $EDITOR_WORKSPACE_ID
wmctrl -s $EDITOR_WORKSPACE_ID

latexrun --clean-all
while true; do
      clear
      echo [+] Started: \$(date "+%Y-%m-%d %H:%M:%S")
      latexrun $DOC_NAME
      jq --raw-output \
         '.tasks | .[] | .deps | map(select(.[0] == "file")) | .[] | .[1] | .[]' \
         latex.out/.latexrun.db > latex.out/.tex-here.depends
      echo [+] Done: \$(date "+%Y-%m-%d %H:%M:%S")
      echo "\n\n"
      inotifywait \
         --quiet \
         --fromfile latex.out/.tex-here.depends \
         --event modify,move_self,delete_self,unmount
      sleep 1
done
read _
EOF

wmctrl -r :ACTIVE: -t $SHELL_WORKSPACE_ID

tmux \
    new-session -s tex-$DOC_NAME -n prog 'git-progress loop' \; \
    new-window -n compile $HELPER_SCRIPT
